services:
  create:
    build:
      context: docker
      dockerfile: Dockerfile
    image: sleep-sounds
    volumes:
      - type: bind
        source: workspace
        target: /workspace
    working_dir: /workspace
    entrypoint: [ "bash", "-c", "/workspace/entrypoint-create.sh" ]

  normalize:
    image: sleep-sounds
    volumes:
      - type: bind
        source: workspace
        target: /workspace
    working_dir: /workspace
    entrypoint: [ "bash", "-c", "/workspace/entrypoint-normalize.sh" ]
